canal: Support for multiple interfaces.

diff --git a/canal b/canal
--- a/canal
+++ b/canal
@@ -3,8 +3,7 @@
 # Switch to this script's directory
 cd "${0%/*}"
 
-export AUTOSSH_FIRST_POLL=60
-export AUTOSSH_POLL=300
+export AUTOSSH_POLL=60
 
 # kill all the children when done
 trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
@@ -17,12 +16,36 @@ then
   exit 1
 fi
 
-my_port=`cat "${infopath}" | head -n1`
+raw_ports=`cat "${infopath}" | head -n1`
+IFS=' ' read -r -a ports <<<${raw_ports}
+
+iface_inets=$(ip addr | awk '/^[0-9]+:/ { 
+  sub(/:/,"",$2); iface=$2 } 
+/^[[:space:]]*inet / { 
+  split($2, a, "/")
+  print a[1], iface
+}')
 
 for lighthouse in $(ls lighthouses/*)
 do
   ip=$(cat "${lighthouse}" | head -n1)
-  autossh -NTR \*:${my_port}:localhost:22 -oStrictHostKeyChecking=accept-new -oExitOnForwardFailure=yes stagecast@${ip} &
+
+  for iface in eno2 usb0
+  do
+    while true; do
+      inet=$(echo ${iface_inets} | grep ${iface} | cut -f1 -d' ')
+
+      if [[ ! -z ${inet} ]]; then
+        autossh -NTR \*:${ports[0]}:localhost:22 -oStrictHostKeyChecking=accept-new -oExitOnForwardFailure=yes -b ${inet} stagecast@${ip} || true
+      else
+        echo "Cannot bind to interface ${iface}. Retrying in 1 minute."
+      fi
+
+      sleep ${AUTOSSH_POLL} # try to reconnect even if the underlying ssh command failed
+    done &
+
+    ports=("${ports[@]:1}")
+  done
 done
 
 wait
